### ISSUE TITLE
@webhook not included in auto-complete

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#604]

**Comment by putorti** [comment]
@rowanseymour Is this working by the way? I'm getting this error even though `@child.webhook` does indeed seem to autocomplete in the new editor.

`error evaluating @child.webhook.body.target_string: object has no property 'webhook'`

Do I need to still set as a flow result? I tried the above and the simpler `@child.webhook.target_string` as well.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/82857/58907712-d40c1700-86dc-11e9-8289-fd481a157f9f.png">

<img width="298" alt="image" src="https://user-images.githubusercontent.com/82857/58907739-dcfce880-86dc-11e9-96ff-deb8160e7eba.png">

**Comment by rowanseymour** [comment]
@putorti we'll update the editor shortly but the expressions that will actually work for getting webhook responses are:

- `@webhook` -> the parsed JSON of the last webhook response
- `@run.results.<resultname>.extra` -> the parsed JSON of the named webhook result in this run
- `@child.run.results.<resultname>.extra` -> the parsed JSON of the named webhook result in the child run
- `@parent.run.results.<resultname>.extra` -> the parsed JSON of the named webhook result in the parent run

**Comment by putorti** [comment]
These are great thanks, I'm not sure if you could access individual web hooks before but this is a game changer and huge step saver.

**Comment by rowanseymour** [comment]
Yeah every response can be stored separately and `@webhook` is just there as a convenience for users who don't have so many webhook calls.

**Comment by ericnewcomer** [comment]
Addressed in #605

**Comment by putorti** [comment]
Is there still no way to pass objects between flows and properly access them using notation that works on `@webhook` or `.extra`?

I'd like to send `@run.results.<resultname>.extra.array[0-2]` to a child flow and be able to parse the objects like I could in the parent flow. Do I need to grab the result, store as JSON, send it, then parse it on the other end? As of yet I haven't figured out anything that lets me do it, nor iterate through that array above for example and call the flow on each object.

**Comment by nicpottier** [comment]
You can save JSON anywhere as a result.

You can then parse it using `parse_json`. 

So if you saved `results.foo` as: `{"key": "bar"}`

You can read it elsewhere with `@(parse_json(results.foo).key)`

**Comment by putorti** [comment]
That's what I thought as well, but, still no luck:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/82857/59626908-0705d000-910b-11e9-9043-428f67c79714.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/82857/59626925-0ff6a180-910b-11e9-86ca-52e2f0654898.png">

**Comment by nicpottier** [comment]
I think you are hanging yourself a big here due to the stringification of JSON.

When you see things like: `{ key: value }` that's RapidPro stringifying your JSON. Note that stringified JSON is NOT JSON however.

So if you want to save real JSON, you need to save something like `@(json(result.webhook.extra))` which will save something that is properly JSON, ie: `{"key": "value"}`

**Comment by nicpottier** [comment]
@rowanseymour one interesting bit with the use case above is that I'm guessing his `parse_json` is returning an error but that's then being masked by us looking at the subkey? Seems we should shortcut there maybe to clarify the real source?

**Comment by putorti** [comment]
Thanks, that was it, I was trying a lot of permutations and lost it. If there was a way in simulator to know the difference, they display exactly the same.

This worked:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/82857/59627441-3a952a00-910c-11e9-89fc-7c4758cb0c4b.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/82857/59627447-3ec14780-910c-11e9-97ed-beb7c3018c1c.png">

**Comment by chris-erickson** [comment]
For me, it's been challenging to not know when I'm dealing with the stringified result of an object, or an object itself (usually when printing a variable in a child flow to examine the parent results).  Have a strategy for that?  A new `is_object()` test?  Auto `jsonify` an object across flows?  Right now we are just making sure to `json` then `parse_json`, but it would seem like one would never want the stringified object in a child result anyways, so that might be nice default behavior.  Would essentially be dehydrating and rehydrating flow vars all the way down, assuming I'm not missing something.

**Comment by nicpottier** [comment]
Key thing to remember is results are always strings. So you aren't seeing any other representation of them when echoing them out. So if they don't have quotes, they don't have quotes.

If you want to double check `JSON(whatevs)` will always give you a JSON representation of an expression, that can always be the guide as to what "type" you are dealing with.

**Comment by rowanseymour** [comment]
@nicpottier `parse_json` (which is using jsonparser) appears to be just ignoring malformed JSON https://github.com/nyaruka/goflow/issues/699

**Comment by nicpottier** [comment]
Just keep repeating to yourself that results are strings, results are strings.

**Comment by nicpottier** [comment]
> Right now we are just making sure to json then parse_json, but it would seem like one would never want the stringified object in a child result anyways, so that might be nice default behavior. 

Having a result be a normal string is the 99% use case, not the exception. Any kind of automatic marshalling would quickly turn into a nightmare that would open up possible ways that people could take advantage of your flows. (IE, if we always treated things that looked like JSON as JSON weird this would happen when people respond with JSON)

**Comment by nicpottier** [comment]
PS. See: https://github.com/nyaruka/goflow/issues/702#issuecomment-503218250

You should actually be able to get parent results via `@parent.run.results.foo.extra.blah` Likely we are going to make it so you can just use `@parent.results.foo.extra.blah`
